export const EVENT_TYPE = {
  MIXPANEL_INIT: 'MIXPANEL_INIT',
  DEVICE_INFO: 'DEVICE_INFO',

  // toolbar
  TOOLBAR_SETTINGS_DIALOG_OPEN: 'TOOLBAR_SETTINGS_DIALOG_OPEN',
  TOOLBAR_SETTINGS_DIALOG_CLOSE: 'TOOLBAR_SETTINGS_DIALOG_CLOSE',

  /// MTP ------------------------------------->
  // actions
  MTP_INITIALIZE_SUCCESS: 'MTP_INITIALIZE_SUCCESS',
  MTP_INITIALIZE_ERROR: 'MTP_INITIALIZE_ERROR',
  MTP_DISPOSE_SUCCESS: 'MTP_DISPOSE_SUCCESS',
  MTP_DISPOSE_ERROR: 'MTP_DISPOSE_ERROR',
  MTP_LIST_STORAGES_SUCCESS: 'MTP_LIST_STORAGES_SUCCESS',
  MTP_LIST_STORAGES_ERROR: 'MTP_LIST_STORAGES_ERROR',
  MTP_LIST_FILES_SUCCESS: 'MTP_LIST_FILES_SUCCESS',
  MTP_LIST_FILES_ERROR: 'MTP_LIST_FILES_ERROR',
  MTP_RENAME_FILE_SUCCESS: 'MTP_RENAME_FILE_SUCCESS',
  MTP_RENAME_FILE_ERROR: 'MTP_RENAME_FILE_ERROR',
  MTP_DELETE_FILE_SUCCESS: 'MTP_DELETE_FILE_SUCCESS',
  MTP_DELETE_FILE_ERROR: 'MTP_DELETE_FILE_ERROR',
  MTP_FILES_EXIST_SUCCESS: 'MTP_FILES_EXIST_SUCCESS',
  MTP_FILES_EXIST_ERROR: 'MTP_FILES_EXIST_ERROR',
  MTP_TRANSFER_FILES_SUCCESS: 'MTP_TRANSFER_FILES_SUCCESS',
  MTP_TRANSFER_FILES_ERROR: 'MTP_TRANSFER_FILES_ERROR',
  MTP_FETCH_DEBUG_REPORT_SUCCESS: 'MTP_FETCH_DEBUG_REPORT_SUCCESS',
  MTP_FETCH_DEBUG_REPORT_ERROR: 'MTP_FETCH_DEBUG_REPORT_ERROR',

  // toolbar
  MTP_TOOLBAR_REFRESH: 'MTP_TOOLBAR_REFRESH',
  MTP_TOOLBAR_FOLDER_UP: 'MTP_TOOLBAR_FOLDER_UP',
  MTP_TOOLBAR_DELETE: 'MTP_TOOLBAR_DELETE',
  MTP_TOOLBAR_GITHUB_TAP: 'MTP_TOOLBAR_GITHUB_TAP',
  MTP_TOOLBAR_STORAGE_DIALOG_OPEN: 'MTP_TOOLBAR_STORAGE_DIALOG_OPEN',
  MTP_TOOLBAR_STORAGE_DIALOG_CLOSE: 'MTP_TOOLBAR_STORAGE_DIALOG_CLOSE',
  MTP_TOOLBAR_MTP_MODE_DIALOG_OPEN: 'MTP_TOOLBAR_MTP_MODE_DIALOG_OPEN',
  MTP_TOOLBAR_MTP_MODE_DIALOG_CLOSE: 'MTP_TOOLBAR_MTP_MODE_DIALOG_CLOSE',

  /// LOCAL ------------------------------------->
  // actions
  LOCAL_LIST_FILES_SUCCESS: 'LOCAL_LIST_FILES_SUCCESS',
  LOCAL_LIST_FILES_ERROR: 'LOCAL_LIST_FILES_ERROR',
  LOCAL_RENAME_FILE_SUCCESS: 'LOCAL_RENAME_FILE_SUCCESS',
  LOCAL_RENAME_FILE_ERROR: 'LOCAL_RENAME_FILE_ERROR',
  LOCAL_DELETE_FILE_SUCCESS: 'LOCAL_DELETE_FILE_SUCCESS',
  LOCAL_DELETE_FILE_ERROR: 'LOCAL_DELETE_FILE_ERROR',
  LOCAL_FILES_EXIST_SUCCESS: 'LOCAL_FILES_EXIST_SUCCESS',
  LOCAL_FILES_EXIST_ERROR: 'LOCAL_FILES_EXIST_ERROR',

  // toolbar
  LOCAL_TOOLBAR_REFRESH: 'LOCAL_TOOLBAR_REFRESH',
  LOCAL_TOOLBAR_FOLDER_UP: 'LOCAL_TOOLBAR_FOLDER_UP',
  LOCAL_TOOLBAR_DELETE: 'LOCAL_TOOLBAR_DELETE',
  LOCAL_TOOLBAR_GITHUB_TAP: 'LOCAL_TOOLBAR_GITHUB_TAP',
};
