export const EVENT_TYPE = {
  INIT: 'INIT',
  DEVICE_INFO: 'DEVICE_INFO',
  REFRESH: 'REFRESH',
  MTP_INITIALIZE_BEGIN: 'MTP_INITIALIZE_BEGIN',
  MTP_INITIALIZE_SUCCESS: 'MTP_INITIALIZE_SUCCESS',
  MTP_INITIALIZE_ERROR: 'MTP_INITIALIZE_ERROR',
};
