export const EVENT_TYPE = {
  // actions
  MIXPANEL_INIT: 'MIXPANEL_INIT',
  DEVICE_INFO: 'DEVICE_INFO',

  // toolbar
  TOOLBAR_SETTINGS_DIALOG_OPEN: 'TOOLBAR_SETTINGS_DIALOG_OPEN',
  TOOLBAR_SETTINGS_DIALOG_CLOSE: 'TOOLBAR_SETTINGS_DIALOG_CLOSE',
  TOOLBAR_SETTINGS_CHANGE: 'TOOLBAR_SETTINGS_CHANGE',

  /// MTP ------------------------------------->
  // actions
  MTP_INITIALIZE_SUCCESS: 'MTP_INITIALIZE_SUCCESS',
  MTP_INITIALIZE_ERROR: 'MTP_INITIALIZE_ERROR',
  MTP_DISPOSE_SUCCESS: 'MTP_DISPOSE_SUCCESS',
  MTP_DISPOSE_ERROR: 'MTP_DISPOSE_ERROR',
  MTP_LIST_STORAGES_SUCCESS: 'MTP_LIST_STORAGES_SUCCESS',
  MTP_LIST_STORAGES_ERROR: 'MTP_LIST_STORAGES_ERROR',
  MTP_LIST_FILES_SUCCESS: 'MTP_LIST_FILES_SUCCESS',
  MTP_LIST_FILES_ERROR: 'MTP_LIST_FILES_ERROR',
  MTP_RENAME_FILE_SUCCESS: 'MTP_RENAME_FILE_SUCCESS',
  MTP_RENAME_FILE_ERROR: 'MTP_RENAME_FILE_ERROR',
  MTP_DELETE_FILE_SUCCESS: 'MTP_DELETE_FILE_SUCCESS',
  MTP_DELETE_FILE_ERROR: 'MTP_DELETE_FILE_ERROR',
  MTP_NEW_FOLDER_SUCCESS: 'MTP_NEW_FOLDER_SUCCESS',
  MTP_NEW_FOLDER_ERROR: 'MTP_NEW_FOLDER_ERROR',
  MTP_FILES_EXIST_SUCCESS: 'MTP_FILES_EXIST_SUCCESS',
  MTP_FILES_EXIST_ERROR: 'MTP_FILES_EXIST_ERROR',
  MTP_TRANSFER_FILES_SUCCESS: 'MTP_TRANSFER_FILES_SUCCESS',
  MTP_TRANSFER_FILES_ERROR: 'MTP_TRANSFER_FILES_ERROR',
  MTP_FETCH_DEBUG_REPORT_SUCCESS: 'MTP_FETCH_DEBUG_REPORT_SUCCESS',
  MTP_FETCH_DEBUG_REPORT_ERROR: 'MTP_FETCH_DEBUG_REPORT_ERROR',

  MTP_COPY_FILES: 'MTP_COPY_FILES',
  MTP_COPY_TO_QUEUE_FILES: 'MTP_COPY_TO_QUEUE_FILES',
  MTP_PASTE_FILES: 'MTP_PASTE_FILES',
  MTP_PASTE_FILES_DIALOG_OPEN: 'MTP_PASTE_FILES_DIALOG_OPEN',
  MTP_PASTE_FILES_DIALOG_CLOSE: 'MTP_PASTE_FILES_DIALOG_CLOSE',

  MTP_DRAG_FILES_STARTED: 'MTP_DRAG_FILES_START',
  MTP_DRAG_FILES_DROPPED: 'MTP_DRAG_FILES_DROPPED',
  MTP_DRAG_FILES_CANCELLED: 'MTP_DRAG_FILES_CANCELLED',

  MTP_RENAME_STARTED: 'MTP_RENAME_STARTED',
  MTP_RENAME_EXIT: 'MTP_RENAME_EXIT',

  MTP_NEW_FOLDER_STARTED: 'MTP_NEW_FOLDER_STARTED',
  MTP_NEW_FOLDER_EXIT: 'MTP_NEW_FOLDER_EXIT',

  MTP_OPEN_DIRECTORY: 'MTP_OPEN_DIRECTORY',
  MTP_OPEN_FILE: 'MTP_OPEN_FILE',

  MTP_BREADCRUMB_PATH_TAP: 'MTP_BREADCRUMB_PATH_TAP',
  MTP_SIDEBAR_PATH_TAP: 'MTP_SIDEBAR_PATH_TAP',

  // toolbar
  MTP_TOOLBAR_REFRESH: 'MTP_TOOLBAR_REFRESH',
  MTP_TOOLBAR_FOLDER_UP: 'MTP_TOOLBAR_FOLDER_UP',
  MTP_TOOLBAR_GITHUB_TAP: 'MTP_TOOLBAR_GITHUB_TAP',

  MTP_DELETE_DIALOG_OPEN: 'MTP_DELETE_DIALOG_OPEN',
  MTP_DELETE_DIALOG_CLOSE: 'MTP_DELETE_DIALOG_CLOSE',

  MTP_TOOLBAR_STORAGE_DIALOG_OPEN: 'MTP_TOOLBAR_STORAGE_DIALOG_OPEN',
  MTP_TOOLBAR_STORAGE_DIALOG_CLOSE: 'MTP_TOOLBAR_STORAGE_DIALOG_CLOSE',
  MTP_TOOLBAR_STORAGE_SELECTED: 'MTP_TOOLBAR_STORAGE_SELECTED',

  MTP_TOOLBAR_MTP_MODE_DIALOG_OPEN: 'MTP_TOOLBAR_MTP_MODE_DIALOG_OPEN',
  MTP_TOOLBAR_MTP_MODE_DIALOG_CLOSE: 'MTP_TOOLBAR_MTP_MODE_DIALOG_CLOSE',
  MTP_MODE_SELECTED: 'MTP_MODE_SELECTED',

  // keymaps
  MTP_KEYMAP_REFRESH: 'MTP_KEYMAP_REFRESH',
  MTP_KEYMAP_FOLDER_UP: 'MTP_KEYMAP_FOLDER_UP',
  MTP_KEYMAP_DELETE: 'MTP_KEYMAP_DELETE',
  MTP_KEYMAP_GITHUB_TAP: 'MTP_KEYMAP_GITHUB_TAP',

  ///
  /// LOCAL ------------------------------------->
  ///
  // actions
  LOCAL_LIST_FILES_SUCCESS: 'LOCAL_LIST_FILES_SUCCESS',
  LOCAL_LIST_FILES_ERROR: 'LOCAL_LIST_FILES_ERROR',
  LOCAL_RENAME_FILE_SUCCESS: 'LOCAL_RENAME_FILE_SUCCESS',
  LOCAL_RENAME_FILE_ERROR: 'LOCAL_RENAME_FILE_ERROR',
  LOCAL_NEW_FOLDER_SUCCESS: 'LOCAL_NEW_FOLDER_SUCCESS',
  LOCAL_NEW_FOLDER_ERROR: 'LOCAL_NEW_FOLDER_ERROR',
  LOCAL_DELETE_FILE_SUCCESS: 'LOCAL_DELETE_FILE_SUCCESS',
  LOCAL_DELETE_FILE_ERROR: 'LOCAL_DELETE_FILE_ERROR',
  LOCAL_FILES_EXIST_SUCCESS: 'LOCAL_FILES_EXIST_SUCCESS',
  LOCAL_FILES_EXIST_ERROR: 'LOCAL_FILES_EXIST_ERROR',

  LOCAL_COPY_FILES: 'LOCAL_COPY_FILES',
  LOCAL_COPY_TO_QUEUE_FILES: 'LOCAL_COPY_TO_QUEUE_FILES',
  LOCAL_PASTE_FILES: 'LOCAL_PASTE_FILES',
  LOCAL_PASTE_FILES_DIALOG_OPEN: 'LOCAL_PASTE_FILES_DIALOG_OPEN',
  LOCAL_PASTE_FILES_DIALOG_CLOSE: 'LOCAL_PASTE_FILES_DIALOG_CLOSE',

  LOCAL_DRAG_FILES_STARTED: 'LOCAL_DRAG_FILES_STARTED',
  LOCAL_DRAG_FILES_DROPPED: 'LOCAL_DRAG_FILES_DROPPED',
  LOCAL_DRAG_FILES_CANCELLED: 'LOCAL_DRAG_FILES_CANCELLED',

  LOCAL_RENAME_STARTED: 'LOCAL_RENAME_STARTED',
  LOCAL_RENAME_EXIT: 'LOCAL_RENAME_EXIT',

  LOCAL_NEW_FOLDER_STARTED: 'LOCAL_NEW_FOLDER_STARTED',
  LOCAL_NEW_FOLDER_EXIT: 'LOCAL_NEW_FOLDER_EXIT',

  LOCAL_OPEN_DIRECTORY: 'LOCAL_OPEN_DIRECTORY',
  LOCAL_OPEN_FILE: 'LOCAL_OPEN_FILE',

  LOCAL_BREADCRUMB_PATH_TAP: 'LOCAL_BREADCRUMB_PATH_TAP',
  LOCAL_SIDEBAR_PATH_TAP: 'LOCAL_SIDEBAR_PATH_TAP',

  // toolbar
  LOCAL_TOOLBAR_REFRESH: 'LOCAL_TOOLBAR_REFRESH',
  LOCAL_TOOLBAR_FOLDER_UP: 'LOCAL_TOOLBAR_FOLDER_UP',
  LOCAL_TOOLBAR_GITHUB_TAP: 'LOCAL_TOOLBAR_GITHUB_TAP',

  LOCAL_DELETE_DIALOG_OPEN: 'LOCAL_DELETE_DIALOG_OPEN',
  LOCAL_DELETE_DIALOG_CLOSE: 'LOCAL_DELETE_DIALOG_CLOSE',

  // keymaps
  LOCAL_KEYMAP_REFRESH: 'LOCAL_KEYMAP_REFRESH',
  LOCAL_KEYMAP_FOLDER_UP: 'LOCAL_KEYMAP_FOLDER_UP',
  LOCAL_KEYMAP_DELETE: 'LOCAL_KEYMAP_DELETE',
};
