export const MTP_ERROR = {
  ErrorGeneral: 'ErrorGeneral',
  ErrorSendObject: 'ErrorSendObject',
  ErrorFileObjectRead: 'ErrorFileObjectRead',
  ErrorFileTransfer: 'ErrorFileTransfer',
  ErrorInvalidPath: 'ErrorInvalidPath',
  ErrorLocalFileRead: 'ErrorLocalFileRead',
  ErrorFilePermission: 'ErrorFilePermission',
  ErrorFileNotFound: 'ErrorFileNotFound',
  ErrorListDirectory: 'ErrorListDirectory',
  ErrorStorageFull: 'ErrorStorageFull',
  ErrorNoStorage: 'ErrorNoStorage',
  ErrorStorageInfo: 'ErrorStorageInfo',
  ErrorDeviceInfo: 'ErrorDeviceInfo',
  ErrorAllowStorageAccess: 'ErrorAllowStorageAccess',
  ErrorMultipleDevice: 'ErrorMultipleDevice',
  ErrorDeviceLocked: 'ErrorDeviceLocked',
  ErrorDeviceSetup: 'ErrorDeviceSetup',
  ErrorMtpChanged: 'ErrorMtpChanged',
  ErrorMtpDetectFailed: 'ErrorMtpDetectFailed',
};
